### ISSUE TITLE
pyrolite_meltsutil.automation: Some calculation errored. And I don't get the calculation results.

### ISSUE THREAD

**Issue by gufan01** [morganjwilliams/pyrolite-meltsutil#7] opened 2021-04-11 07:37 UTC
**Describe the bug**
I install the aphlamelt first and then do the calculation that you post. The following is the code.

**To Reproduce**
The following is the code:

from pyrolite.util.meta import stream_log
from pyrolite_meltsutil.download import install_melts
from pyrolite_meltsutil.util.general import pyrolite_meltsutil_datafolder

if not (pyrolite_meltsutil_datafolder(subfolder="localinstall")).exists():
    stream_log("pyrolite-meltsutil", level="INFO")  # logger for output info
    install_melts(local=True)  # install a copy of melts to pyrolite data folder

import os, sys
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from pyrolite_meltsutil.automation import MeltsBatch

from pyrolite_meltsutil.util.synthetic import isobaricGaleMORBexample

MORB = isobaricGaleMORBexample(title="Gale2013MORB")

from pyrolite_meltsutil.env import MELTS_Env

env = MELTS_Env()
env.VERSION = "MELTS"
env.MODE = "isobaric"
env.MINP = 5000
env.MAXP = 10000
env.MINT = 500
env.MAXT = 1500
env.DELTAT = -10
env.DELTAP = 0

experiment_dir = "Batch" # I create a local folder and then run the batch model.

batch = MeltsBatch(
    MORB,
    default_config={  # things that won't change between experiments
        "Initial Temperature": 1400,
        "Final Temperature": 800,
        "modes": ["isobaric", "fractionate solids"],
    },
    config_grid={  # things that change between experiments
        "Initial Pressure": [5000, 7000],
        "Log fO2 Path": [None, "FMQ"],
        "modifychem": [None, {"H2O": 0.5}],
    },
    env=env,
    fromdir=experiment_dir,
)

batch.run(overwrite=True)  #  Resut "WARNING:pyrolite_meltsutil.automation:Some calculations errored:" I don't get the calculation results.

**Expected behavior**
Different aphlamelt version under in the WSL. The install aphlamelt is not run.

**Environment:**
 - OS: WSL, Ubuntu 16.04
 - Python Version [e.g. 3.8]
 - Pyrolite Version [e.g. 0.1.6]

**Additional Context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by morganjwilliams** [comment] 2021-04-11 23:26
Hi @gufan01!

Could you let me know which versions of `pyrolite` and `pyrolite-meltsutil` you're using? I've not recently updated `pyrolite-meltsutil` so there could be some incompatibilities. 

Also note that if you've separately installed `alphaMELTS`  (<2) somewhere you'll need to specify where that is in order to use it; generally `meltsutil` will be used with a separate version installed within the python package folder, but it should be fine either way (maybe just a bit clunky to sort out as it is right now). Note that the script as above will install a local copy of alphaMELTS within the `meltsutil` folder if one doesn't already exist. Also note that it will not deal with potential numerical issues with `alphaMELTS` runs - if for some reason the experiments don't run  (or hang) due to convergence issues or similar then you'll get no results. This often happens with stranger compositions, but will also occur relatively frequently with normal compositions - generally the approach would be to run things which fail directly with `alphaMELTS` to debug the issues, and potentially control the flow of the experiment (skipping a small temperature range during crystallization, for example).

Also consider updating the logger to the `DEBUG` level to get more information.
```
stream_log("pyrolite-meltsutil", level="DEBUG")
```

The package is due for an update, but I'm not sure when I'll have time to get back to this. There's plans to make some changes for working with `alphaMELTS 2` and the Python client but these will be a while off.

**Comment by gufan01** [comment] 2021-04-12 03:16
> Hi @gufan01!
> 
> Could you let me know which versions of `pyrolite` and `pyrolite-meltsutil` you're using? I've not recently updated `pyrolite-meltsutil` so there could be some incompatibilities.
> 
> Also note that if you've separately installed `alphaMELTS` (<2) somewhere you'll need to specify where that is in order to use it; generally `meltsutil` will be used with a separate version installed within the python package folder, but it should be fine either way (maybe just a bit clunky to sort out as it is right now). Note that the script as above will install a local copy of alphaMELTS within the `meltsutil` folder if one doesn't already exist. Also note that it will not deal with potential numerical issues with `alphaMELTS` runs - if for some reason the experiments don't run (or hang) due to convergence issues or similar then you'll get no results. This often happens with stranger compositions, but will also occur relatively frequently with normal compositions - generally the approach would be to run things which fail directly with `alphaMELTS` to debug the issues, and potentially control the flow of the experiment (skipping a small temperature range during crystallization, for example).
> 
> Also consider updating the logger to the `DEBUG` level to get more information.
> 
> ```
> stream_log("pyrolite-meltsutil", level="DEBUG")
> ```
> 
> The package is due for an update, but I'm not sure when I'll have time to get back to this. There's plans to make some changes for working with `alphaMELTS 2` and the Python client but these will be a while off.

The version of pyrolite I used is 0.2.8, and the pyrolite-meltsutil is 0.1.6. Based on your suggestion I update the pyrolite (0.3.0), all of the code cannot be run.
```
ImportError: cannot import name 'ToLogger' from 'pyrolite.util.meta'
```

**Comment by morganjwilliams** [comment] 2021-04-12 03:23
The current version of `pyrolite-meltsutil` is unlikely to be completely compatible with `pyrolite>0.2.5` (released about the same time), and errors about logging modules are expected for v0.3.0.

**Comment by gufan01** [comment] 2021-04-12 03:33
> The current version of `pyrolite-meltsutil` is unlikely to be completely compatible with `pyrolite>0.2.5` (released about the same time), and errors about logging modules are expected for v0.3.0.

Thanks for your reply. Hope you have time to update the  `pyrolite-meltsutil` soon. Thanks again.

**Comment by morganjwilliams** [comment] 2021-04-12 03:38
Should have time to make a bugfix release which deals with the logging errors, but I'll need to switch over the continuous integration (which might take a bit of fiddling). I'll be back in the office next week so keep an eye out after that.

**Comment by morganjwilliams** [comment] 2021-04-22 05:27
Hi @gufan01! I've updated the `develop` branch to line up with `pyrolite 0.3.0` and fixed the CI. You can install a development version using:

```pip install git+git://github.com/morganjwilliams/pyrolite-meltsutil.git@develop#egg=pyrolite_meltsutil```

This will address the version-related issues, and then we can have another look at the issues you're having.

**Comment by gufan01** [comment] 2021-04-22 05:38
> Hi @gufan01! I've updated the `develop` branch to line up with `pyrolite 0.3.0` and fixed the CI. You can install a development version using:
> 
> `pip install git+git://github.com/morganjwilliams/pyrolite-meltsutil.git@develop#egg=pyrolite_meltsutil`
> 
> This will address the version-related issues, and then we can have another look at the issues you're having.

Ok. Thanks very much. I will try it.

**Comment by gufan01** [comment] 2021-04-22 05:56
> Hi @gufan01! I've updated the `develop` branch to line up with `pyrolite 0.3.0` and fixed the CI. You can install a development version using:
> 
> `pip install git+git://github.com/morganjwilliams/pyrolite-meltsutil.git@develop#egg=pyrolite_meltsutil`
> 
> This will address the version-related issues, and then we can have another look at the issues you're having.

Hi Morgen, 

I have tried to use the update 'pyrolite_meltsutil' to install the aphlamelt. But it also failed. The following is code:

Input: `from pyrolite.util.meta import stream_log` 
The output is  "ImportError: cannot import name 'stream_log' from 'pyrolite.util.meta".

All the other codes can be run, but, In the outlog.log file, some warnings were shown:
"2021-04-11 15:12:20,702 - pyrolite_meltsutil.automation - WARNING - Some calculations errored:
2021-04-11 15:12:20,702 - pyrolite_meltsutil.automation - WARNING - Gale2013MORBisobarfrac5-5kbar1300-800CFMQ363f3d0a0b
2021-04-11 15:12:20,703 - pyrolite_meltsutil.automation - WARNING - Gale2013MORBisobarfrac5-5kbar1300-800CFMQ4689ca6fc3
2021-04-11 15:17:09,864 - pyrolite_meltsutil.automation - WARNING - Some calculations errored:
2021-04-11 15:17:09,864 - pyrolite_meltsutil.automation - WARNING - Some calculations errored:"

I don't think I have got the calculation results and also fail to install the aphlamelt.

Thanks.

**Comment by morganjwilliams** [comment] 2021-04-22 06:05
For the streaming the logger, you can use (for pyrolite 0.3.0):
```from pyrolite.util.log import stream_log```

Just a quick note that reinstalling `pyrolite-meltsutil` will not reinstall `alphaMELTS`, and the [`install_melts()`](https://pyrolite-meltsutil.readthedocs.io/en/develop/api/API.html#pyrolite_meltsutil.download.install_melts) function will require that you have a version of `perl` installed and accessible via that command from the command line (generally I'd use `install_melts(local=True)` to make sure it's within the `pyrolite-meltsutil` folder and easy to find; you can find which folder it uses with `pyrolite_meltsutil.util.general.pyrolite_meltsutil_datafolder()`)

**Comment by morganjwilliams** [comment] 2021-04-22 06:06
Also, some calculations may just error with `alphaMELTS`; I've found that sometimes up to half of my runs won't go anywhere due to some numerical issue or crash.

**Comment by gufan01** [comment] 2021-04-23 06:17
> For the streaming the logger, you can use (for pyrolite 0.3.0):
> `from pyrolite.util.log import stream_log`
> 
> Just a quick note that reinstalling `pyrolite-meltsutil` will not reinstall `alphaMELTS`, and the [`install_melts()`](https://pyrolite-meltsutil.readthedocs.io/en/develop/api/API.html#pyrolite_meltsutil.download.install_melts) function will require that you have a version of `perl` installed and accessible via that command from the command line (generally I'd use `install_melts(local=True)` to make sure it's within the `pyrolite-meltsutil` folder and easy to find; you can find which folder it uses with `pyrolite_meltsutil.util.general.pyrolite_meltsutil_datafolder()`)

Hi Morgan,

I have used the method you mentioned and I have installed the `alphamelts` into the data folder. I tried to run the command of `batch.run(overwrite=True)`, but I just got the `environment.txt`, `xxxx.melts`, `xxxx.melts_bak` and `logfile.text` file, and I didn't obtain the output files from `alphamelts`. The attached is the code.

[automation.zip](https://github.com/morganjwilliams/pyrolite-meltsutil/files/6363177/automation.zip)

**Comment by morganjwilliams** [comment] 2021-04-23 07:06
Thanks @gufan01, I'll take a look and see if I can pick up any issues.

**Comment by morganjwilliams** [comment] 2021-04-23 08:38
@gufan01 - just checking, do you have a version of `perl` installed locally which is accessible via a typical command prompt? I've recently had to set up a new computer and didn't have this installed - and could replicate what you see that way. It'll create all the directories but when it gets to call `alphaMELTS`, it does so through the supplied `perl` scripts - I get `OSError`s related to not being able to find `perl` (although the error messages typically refer to stdin/stdout pipe communication errors because of processes which didn't initiate because of the failed command..).

I installed a portable version of Strawberry Perl (if you specifically wanted this version, you can find it under [releases](https://strawberryperl.com/releases.html)) and was able to generate all of the expected tables after that. I've mentioned `perl` in a few places in the docs, but perhaps I should add a bit more on this aspect.

**Comment by gufan01** [comment] 2021-04-23 09:22
> @gufan01 - just checking, do you have a version of `perl` installed locally which is accessible via a typical command prompt? I've recently had to set up a new computer and didn't have this installed - and could replicate what you see that way. It'll create all the directories but when it gets to call `alphaMELTS`, it does so through the supplied `perl` scripts - I get `OSError`s related to not being able to find `perl` (although the error messages typically refer to stdin/stdout pipe communication errors because of processes which didn't initiate because of the failed command..).
> 
> I installed a portable version of Strawberry Perl (if you specifically wanted this version, you can find it under [releases](https://strawberryperl.com/releases.html)) and was able to generate all of the expected tables after that. I've mentioned `perl` in a few places in the docs, but perhaps I should add a bit more on this aspect.

I run those codes under the WSL with ubuntu 18.04. I installed `perl` with conda, and I can call the perl using the WSL.

**Comment by morganjwilliams** [comment] 2021-04-27 01:40
Ok, thanks for the info. I'll see if I can follow up on a copy of WSL, and otherwise will send some more debugging info your way. Will also see if I might need to update the tests to see whether I can pick up anything specific happening on Linux.

**Comment by morganjwilliams** [comment] 2021-05-05 03:29
@gufan01 I've had a look at this in Ubuntu (via Binder, don't have a running WSL at the moment) and again could reproduce the results if _alphaMELTS itself_ wasn't installed before the example was run. I'll look at adding a warning to check for a valid installation so this is evident if something like this happens in the future.

Could you check what's within the `pyrolite-meltsutil/data/locallinstall` folder, and if there seems to be nothing there run the following?

```python
from pyrolite.util.log import stream_log
from pyrolite_meltsutil.download import install_melts

stream_log("pyrolite-meltsutil.download", level="DEBUG")  # logger for output info
install_melts(local=True)  # install a copy of melts to pyrolite data folder
```
If that folder has the expected `.command` files etc, try adding the following loggers to the top your example and see what they spit out:
```python
from pyrolite.util.log import stream_log, Handle

stream_log(Handle(__name__, level='DEBUG') ) # logger for automation example (__name__ will be `__main__`)
stream_log('pyrolite_meltsutil.automation.process', level='DEBUG') # logger for automation.process submodule
```
In particular the second logger should give you a series of commands you _should_ be able to use to better debug what's going on. For example, the output I get on Binder is:
```
pyrolite_meltsutil.automation.process - DEBUG: Setting working directory: /home/jovyan/binder/src/pyrolite-meltsutil/pyrolite_meltsutil/data/data_examples/montecarlo/013ada1e1d
pyrolite_meltsutil.automation.process - DEBUG: Using local executable: run_alphamelts.command @ /home/jovyan/binder/src/pyrolite-meltsutil/pyrolite_meltsutil/data/localinstall/links
pyrolite_meltsutil.automation.process - DEBUG: Setting meltsfile: Gale2013MORB-0isobar5-5kbar1300-800CFMQ013ada1e1d.melts
pyrolite_meltsutil.automation.process - DEBUG: Setting environment file: environment.txt
pyrolite_meltsutil.automation.process - DEBUG: Starting Melts Process with: run_alphamelts.command -m Gale2013MORB-0isobar5-5kbar1300-800CFMQ013ada1e1d.melts -f environment.txt
pyrolite_meltsutil.automation.process - DEBUG: Process Started with ID 1323
pyrolite_meltsutil.automation.process - DEBUG: Reproduce using: cd /home/jovyan/binder/src/pyrolite-meltsutil/pyrolite_meltsutil/data/data_examples/montecarlo/013ada1e1d && /home/jovyan/binder/src/pyrolite-meltsutil/pyrolite_meltsutil/data/localinstall/links/run_alphamelts.command -m Gale2013MORB-0isobar5-5kbar1300-800CFMQ013ada1e1d.melts -f environment.txt
pyrolite_meltsutil.automation.process - DEBUG: Passing Inital Variables: 1 Gale2013MORB-0isobar5-5kbar1300-800CFMQ013ada1e1d.melts
pyrolite_meltsutil.automation.process - DEBUG: Terminating alphamelts
```
## TODO
- [x] @morganjwilliams Check that `pryolite-meltsutil` can directly use an existing `alphaMELTS` installation by specifying its path.
- [x] @morganjwilliams Add warning to `pyrolite-meltsutil.automation` to warn when `alphaMELTS` doesn't seem to be installed.

**Comment by gufan01** [comment] 2021-05-05 07:24
@morganjwilliams  Follow your codes, I succeeded in getting results under the WSL with Unbuntu 18.04. It's so cool. Thanks. And all of my next simulations will be finished using `pryolite-metlsutil`.

By the way, when will the `alphaMELTS 2` be available in the `pryolite-metlsutil`?

**Comment by morganjwilliams** [comment] 2021-05-05 07:32
Great @gufan01! Apologies it took so long to sorting it out for you, this project isn't widely used at the moment. If you find any of your future experiments fail for some reason do try and use that logging code above - it'll i) give you more information about what's going on and ii) provide some better info to get you some guidance here should you need it.

Regarding `alphaMELTS 2`, I haven't really played with it yet - but I've had a quick email exchange with Paula around this, and the answer is 'perhaps sometime after Goldschmidt'. I want to refine how these are put together based on the menu structures/command line API, and that might be a good opportunity to generalize what I've done in the package so far. In an ideal world I'd probably just hook into the `alphaMELTS for Python` end of things but for the moment wrapping the executables is all I've managed to do.

Given the issue seems to be solved, I'll close this one and look at addressing the TODO items I listed above.

**Closed as completed by morganjwilliams** 2021-05-05 07:32 UTC
Labels: bug

**Comment by morganjwilliams** [comment] 2021-05-05 08:18
@gufan01 just confirming that using the development version you should now be able to specify an external executable using `MeltsBatch` and related classes (so you can use just one existing `alphaMELTS` installation, if you already have one):
```python
batch = MeltsBatch(
    MORB,
    default_config={  # things that won't change between experiments
        "Initial Temperature": 1400,
        "Final Temperature": 800,
        "modes": ["isobaric", "fractionate solids"],
    },
    env=env,
    fromdir=experiment_dir,
    executable="./path/to/melts/executable/run_alphamelts.command"
)
```
And that if you're missing either `perl` or `run_alphamelts.command` (or `run_alphamelts.bat` on Windows) it should warn you about that.
